version: "3"
services:
  app:
    build: .
    image: karllhughes/news:latest
    ports:
    - "1337:1337"
    env_file:
    - ./.env.local
    volumes:
    - ./:/app
    command: node node_modules/.bin/nodemon ./app.js 0.0.0.0 1337
  mongo:
    image: mongo:4.0
    volumes:
    - db:/data/db
    ports:
    - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
volumes:
  db:
