version: "3"
services:
  app:
    build: .
    ports:
    - "1337:1337"
    volumes:
    - ./:/app
  mongo:
    image: mongo:3.2-jessie
    volumes:
    - db:/data/db
    ports:
    - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
volumes:
  db:
